spring:
  datasource:
    url: jdbc:mysql://localhost:3306/forecast
    username: ${USERNAME_MYSQL_DB}
    password: ${PASSWORD_MYSQL_DB}
  jpa:
    show-sql: true

api:
  weather:
    api-end-point: https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/
    location: Minsk
    retry: 0 0 */1 * * ? #Every hour
    api-key: 2QUYFX2HYSTCNBK9N5DDF86W4
    unit-group: metric
    include: days
    content-type: json
    period: today
